/**
 * Shared marker constants for generated-file detection and footer stamping.
 * Centralised to avoid duplication across generators, adapters, and ingest.
 */
import { readFile } from "node:fs/promises";

/** Sentinel embedded in every file we generate. */
export const MARKER = "Generated by memories.sh";

/** HTML-comment footer appended to generated markdown/mdc files. */
export function makeFooter(): string {
  return `\n<!-- ${MARKER} at ${new Date().toISOString()} -->`;
}

/**
 * Check whether a file on disk contains our generation marker.
 * Returns `false` when the file doesn't exist or can't be read.
 */
export async function hasOurMarker(filePath: string): Promise<boolean> {
  try {
    const content = await readFile(filePath, "utf-8");
    return content.includes(MARKER);
  } catch {
    return false;
  }
}
