import { mkdtempSync, mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, it, expect } from "vitest";
import {
  toolSupportsMcp,
  toolSupportsGeneration,
  parseConfigFile,
  installGlobalSkillsGuides,
} from "./setup.js";
import type { Tool } from "./setup-tools.js";

const cursorTool: Tool = {
  name: "Cursor",
  detectPaths: [".cursor"],
  mcpConfigPath: ".cursor/mcp.json",
  mcpConfigFormat: "cursor",
  generateCmd: "cursor",
};

const copilotTool: Tool = {
  name: "GitHub Copilot",
  detectPaths: [".github/copilot-instructions.md"],
  instructionFile: ".github/copilot-instructions.md",
  generateCmd: "copilot",
};

const noGenTool: Tool = {
  name: "Test Tool",
  detectPaths: [".test"],
};

describe("toolSupportsMcp", () => {
  it("returns true for tool with mcpConfigPath and mcpConfigFormat", () => {
    expect(toolSupportsMcp(cursorTool)).toBe(true);
  });

  it("returns false for tool without mcpConfigPath", () => {
    expect(toolSupportsMcp(copilotTool)).toBe(false);
  });
});

describe("toolSupportsGeneration", () => {
  it("returns true for tool with generateCmd", () => {
    expect(toolSupportsGeneration(cursorTool)).toBe(true);
  });

  it("returns false for tool without generateCmd", () => {
    expect(toolSupportsGeneration(noGenTool)).toBe(false);
  });
});

describe("parseConfigFile", () => {
  it("parses valid JSON", () => {
    const result = parseConfigFile('{"mcpServers": {}}');
    expect(result.mcpServers).toEqual({});
  });

  it("parses JSONC with comments", () => {
    const jsonc = `{
      // This is a comment
      "mcpServers": {}
    }`;
    const result = parseConfigFile(jsonc);
    expect(result.mcpServers).toEqual({});
  });

  it("handles block comments", () => {
    const jsonc = `{
      /* block comment */
      "servers": {"test": {}}
    }`;
    const result = parseConfigFile(jsonc);
    expect(result.servers).toBeDefined();
  });
});

describe("installGlobalSkillsGuides", () => {
  it("writes SKILLS.md for detected global tool config paths", async () => {
    const homeDir = mkdtempSync(join(tmpdir(), "memories-global-skills-"));
    mkdirSync(join(homeDir, ".claude"), { recursive: true });

    const result = await installGlobalSkillsGuides({
      homeDir,
      tools: [
        {
          name: "Claude Code",
          detectPaths: [".claude"],
          globalDetectPaths: [".claude"],
        },
      ],
      commandExistsFn: () => false,
    });

    const skillsPath = join(homeDir, ".claude", "SKILLS.md");
    expect(result.created).toContain(skillsPath);
    expect(existsSync(skillsPath)).toBe(true);

    const content = readFileSync(skillsPath, "utf-8");
    expect(content).toContain("memories recall");
    expect(content).toContain("Generated by memories.sh");
  });

  it("does not overwrite user-authored SKILLS.md files", async () => {
    const homeDir = mkdtempSync(join(tmpdir(), "memories-global-skills-user-"));
    const skillsPath = join(homeDir, ".cursor", "SKILLS.md");
    mkdirSync(join(homeDir, ".cursor"), { recursive: true });
    writeFileSync(skillsPath, "# My custom skills\n", "utf-8");

    const result = await installGlobalSkillsGuides({
      homeDir,
      tools: [
        {
          name: "Cursor",
          detectPaths: [".cursor"],
          globalDetectPaths: [".cursor"],
        },
      ],
      commandExistsFn: () => false,
    });

    expect(result.skipped).toContain(skillsPath);
    expect(readFileSync(skillsPath, "utf-8")).toBe("# My custom skills\n");
  });

  it("creates global SKILLS.md for command-detected tools", async () => {
    const homeDir = mkdtempSync(join(tmpdir(), "memories-global-skills-codex-"));

    const result = await installGlobalSkillsGuides({
      homeDir,
      tools: [
        {
          name: "Agent Harness (.agents)",
          detectPaths: [".codex"],
          detectCommands: ["codex"],
        },
      ],
      commandExistsFn: (command) => command === "codex",
    });

    const skillsPath = join(homeDir, ".codex", "SKILLS.md");
    expect(result.created).toContain(skillsPath);
    expect(existsSync(skillsPath)).toBe(true);
  });
});
